name: "[maimai] Fetch new songs"

on:
  schedule:
    - cron: '0 0-5 * * 3-5'
  workflow_dispatch:

jobs:
  fetch_songs:
    name: Fetch latest song list from SEGA
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
          echo "Asia/Tokyo" | sudo tee /etc/timezone

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git user
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout existing branch or create new
        run : |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/maimai-staging; then
            git switch maimai-staging
            git rebase origin/master
          else
            git checkout -b maimai-staging
          fi

          # git pull origin maimai-staging
          # git push --force --set-upstream origin maimai-staging

      - name: Run main script and capture output
        run: |
          python -u scripts/update-songs.py --maimai --nocolors --escape --markdown --no_timestamp --no_verbose 2>&1 | tee output.log

      - name: Extract datestamp from script output
        id: extract_date
        run: |
          echo "datestamp=$(cat maimai/data/music-ex.json | jq '.[-1].date_added | tonumber')" >> "$GITHUB_OUTPUT"
          # Use today's date instead because maimai default json doesn't have date data...
          # echo "datestamp=$(date '+%Y%m%d')" >> "$GITHUB_OUTPUT"


      - name: Commit changes
        id: commit_changes
        env:
          UNIQUE_STRING: ${{ github.run_id }}-${{ github.run_attempt }}
        run: |
          git add .

          if output=$(git status --porcelain) && [ -z "$output" ]; then
            echo "HAS_DIFFS=false" >> "$GITHUB_OUTPUT"
            echo "No changes. Skipping PR request"
          else
            git commit -m "data(maimai): [bot] add song data ${{ steps.extract_date.outputs.DATESTAMP }}"
            git push origin maimai-staging --force-with-lease
            echo "Commited changes."
            echo "HAS_DIFFS=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout existing PR or create new
        if: steps.commit_changes.outputs.HAS_DIFFS == 'true'
        run: |
          python scripts/post-pr.py \
            --head "maimai-staging" \
            --base "${{ github.ref_name }}" \
            --title "[Automation] maimai: Add new songs (${{ steps.extract_date.outputs.DATESTAMP }})" \
            --log-file "output.log"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

