name: "[maimai] Update constants"

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch_constants:
    name: Fetch latest chart constants
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
          echo "Asia/Tokyo" | sudo tee /etc/timezone

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git user
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout existing branch or create new
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/maimai/constants; then
            git switch maimai/constants
            git rebase origin/main
          else
            git checkout -b maimai/constants origin/main
          fi

      - name: Run constants script and capture output
        run: |
          python -u scripts/update-const.py --maimai --all --nocolors --escape --markdown --no_timestamp --no_verbose 2>&1 | tee output.log

      - name: Commit changes
        id: commit_changes
        run: |
          git add .

          if output=$(git status --porcelain) && [ -z "$output" ]; then
            echo "HAS_DIFFS=false" >> "$GITHUB_OUTPUT"
            echo "No changes. Skipping PR request"
          else
            git commit -m "data(maimai): [bot] update song constants"
            git push origin maimai/constants --force-with-lease -u
            echo "Committed changes."
            echo "HAS_DIFFS=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout existing PR or create new
        if: steps.commit_changes.outputs.HAS_DIFFS == 'true'
        run: |
          python scripts/post-pr.py \
            --head "maimai/constants" \
            --base "main" \
            --title "[Automation] maimai: Update chart constants" \
            --log-file "output.log"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

